"""
CyberSentinel AI — Gemini AI Security Analyst Service.

Interprets deterministic model forecasts and telemetry using Google's Gemini API
with strict grounding against CyberSentinel empirical world-model outputs.

Constraints:
  - ZERO hallucination: All stages, scores, and probabilities are sourced from EvidenceService.
  - Safe fallback: If Gemini is unavailable or unconfigured, falls back to deterministic analysis.
  - Security: Never exposes or logs the GEMINI_API_KEY.
"""

from __future__ import annotations

import collections
import logging
import os
import time
from typing import Any, Dict, List, Optional
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the CyberSentinel AI Security Analyst, an expert SOC co-pilot embedded within the CyberSentinel AI World-Model Platform.
Your purpose is to explain, interpret, and provide recommended defensive playbooks grounded strictly in the deterministic machine learning telemetry and stage predictions supplied to you.

MANDATORY OPERATIONAL RULES:
1. STRICT GROUNDING: You must NEVER fabricate, guess, or modify any attack stage, risk score, attack probability, model confidence, MITRE technique ID, or telemetry metric. The verified evidence provided in the prompt is the absolute source of truth generated by CyberSentinel's CyberWorldModelV2 and RiskEngine.
2. INSUFFICIENT EVIDENCE: If telemetry or model evidence is missing or insufficient, state explicitly: "Insufficient telemetry/model evidence is available to determine this."
3. DEFENSIVE RECOMMENDATIONS: Provide concrete, actionable, professional SOC actions based strictly on the current stage and MITRE techniques identified.
4. STRUCTURE: Keep responses well-structured and concise with:
   - **Current Assessment**: Exact stage, risk score, and attack probability from evidence.
   - **Empirical Indicators**: Notable telemetry shifts or feature deltas.
   - **Tactical Analysis**: Why the model reached this conclusion based on the evidence.
   - **Recommended SOC Actions**: Defensive mitigations (firewall, isolation, credential reset, SIEM query).
5. DO NOT cite MITRE techniques not present in the verified evidence or standard mappings of the identified stage.
"""

# Deterministic SOC action recommendations by attack stage
STAGE_ACTIONS: Dict[str, List[str]] = {
    "Reconnaissance": [
        "Enable aggressive rate-limiting on external perimeter interfaces.",
        "Inspect perimeter firewall logs for port/syn sweep patterns.",
        "Verify exposed surface and close unnecessary listening ports.",
    ],
    "Weaponization": [
        "Review inbound email attachments and quarantine suspicious archives.",
        "Scan endpoint storage for newly staged artifacts or staging directories.",
        "Update endpoint detection signatures and audit delivery channels.",
    ],
    "Delivery": [
        "Quarantine matching message IDs and block sender domains in secure email gateway.",
        "Revoke access tokens for affected endpoints and isolate suspected host.",
        "Check web proxy logs for related external download requests.",
    ],
    "Exploitation": [
        "Immediately isolate compromised host from corporate subnet.",
        "Kill offending process trees and dump memory for forensic capture.",
        "Patch targeted vulnerability (CVE) across peer infrastructure.",
    ],
    "Installation": [
        "Inspect registry Run keys, scheduled tasks, and daemon persistence hooks.",
        "Revoke persistence mechanisms and remove unauthorized binaries.",
        "Perform full endpoint EDR artifact scan on adjacent hosts.",
    ],
    "Command_and_Control": [
        "Sever outbound C2 beaconing IP/domain on boundary egress firewalls.",
        "Reset administrative credentials associated with the compromised asset.",
        "Inspect DNS query logs for DGA or unusual encrypted external tunnels.",
    ],
    "Actions_on_Objectives": [
        "Trigger immediate emergency incident response protocol (P1 Critical).",
        "Block outbound data exfiltration channels and isolate backup repositories.",
        "Initiate data integrity verification and notify CISO / incident commander.",
    ],
    "Benign": [
        "Continue normal telemetry monitoring; all metrics remain within baseline tolerance.",
        "No active defensive countermeasures required at this time.",
    ],
}


class GeminiService:
    """Manages Gemini client communication, rate limiting, and grounded reasoning."""

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None) -> None:
        self.api_key = (api_key or os.getenv("GEMINI_API_KEY", "")).strip()
        self.model_name = (model or os.getenv("GEMINI_MODEL", "gemini-3.6-flash")).strip()
        self._client = None
        self._init_client()
        self._query_timestamps: collections.deque = collections.deque(maxlen=60)
        self.rate_limit_per_minute = 30

    def _init_client(self) -> None:
        if self.api_key:
            try:
                from google import genai
                self._client = genai.Client(api_key=self.api_key)
                logger.info("[GeminiService] Initialized Google GenAI client with model: %s", self.model_name)
            except Exception as exc:
                logger.warning("[GeminiService] Failed to initialize Google GenAI client: %s", exc)
                self._client = None
        else:
            logger.info("[GeminiService] No GEMINI_API_KEY found; operating in deterministic fallback mode.")
            self._client = None

    def get_status(self) -> Dict[str, Any]:
        """Return connectivity and configuration status."""
        is_configured = bool(self.api_key)
        return {
            "status": "online" if (self._client is not None) else ("fallback" if is_configured else "offline"),
            "model": self.model_name,
            "available": self._client is not None,
            "api_key_configured": is_configured,
            "rate_limit_rpm": self.rate_limit_per_minute,
        }

    def _check_rate_limit(self) -> bool:
        """Returns True if within rate limit, False if limit exceeded."""
        now = time.time()
        # Evict timestamps older than 60s
        while self._query_timestamps and now - self._query_timestamps[0] > 60:
            self._query_timestamps.popleft()
        if len(self._query_timestamps) >= self.rate_limit_per_minute:
            return False
        self._query_timestamps.append(now)
        return True

    def generate_response(
        self,
        grounded_prompt: str,
        evidence: Dict[str, Any],
        user_message: str,
    ) -> Dict[str, Any]:
        """
        Generate grounded response from Gemini or fallback to deterministic engine.
        """
        # Validate message length
        sanitized_query = (user_message or "").strip()[:2000]
        if not sanitized_query:
            return {
                "answer": "Please provide an inquiry or request for the security analyst.",
                "llm_backend": "none",
                "model": self.model_name,
                "evidence": evidence,
                "fallback": True,
            }

        # Check rate limit
        if not self._check_rate_limit():
            return {
                "answer": (
                    "Rate limit reached (30 queries/minute). Please pause for a few seconds.\n\n"
                    + self._deterministic_fallback(evidence, sanitized_query)
                ),
                "llm_backend": "rate_limited_fallback",
                "model": self.model_name,
                "evidence": evidence,
                "fallback": True,
            }

        # If client available, attempt Gemini generation
        if self._client is not None:
            try:
                response = self._client.models.generate_content(
                    model=self.model_name,
                    contents=grounded_prompt,
                    config={
                        "system_instruction": SYSTEM_PROMPT,
                        "temperature": 0.2,  # Low temperature for strict adherence to facts
                    },
                )
                answer_text = response.text if response and response.text else ""
                if answer_text:
                    return {
                        "answer": answer_text,
                        "llm_backend": "gemini",
                        "model": self.model_name,
                        "evidence": evidence,
                        "fallback": False,
                    }
            except Exception as exc:
                logger.warning("[GeminiService] Gemini call failed: %s. Using deterministic fallback.", exc)
                # Attempt alternative models in resilient cascade
                fallback_models = ["gemini-3.6-flash", "gemini-flash-latest", "gemini-2.0-flash", "gemini-1.5-flash"]
                for alt_model in fallback_models:
                    if alt_model != self.model_name:
                        try:
                            logger.info("[GeminiService] Retrying with model: %s", alt_model)
                            alt_resp = self._client.models.generate_content(
                                model=alt_model,
                                contents=grounded_prompt,
                                config={
                                    "system_instruction": SYSTEM_PROMPT,
                                    "temperature": 0.2,
                                },
                            )
                            if alt_resp and alt_resp.text:
                                return {
                                    "answer": alt_resp.text,
                                    "llm_backend": "gemini",
                                    "model": alt_model,
                                    "evidence": evidence,
                                    "fallback": False,
                                }
                        except Exception:
                            pass

        # Deterministic fallback
        fallback_msg = (
            "Gemini analyst unavailable. CyberSentinel deterministic intelligence remains operational.\n\n"
            + self._deterministic_fallback(evidence, sanitized_query)
        )
        return {
            "answer": fallback_msg,
            "llm_backend": "deterministic_fallback",
            "model": "cybersentinel_rule_engine",
            "evidence": evidence,
            "fallback": True,
        }

    def _deterministic_fallback(self, evidence: Dict[str, Any], user_message: str) -> str:
        """
        Deterministic, rule-based reasoning engine ensuring 100% availability
        even during internet loss or API unavailability.
        """
        if not evidence.get("has_sufficient_evidence"):
            return (
                "**Current Assessment**: Insufficient telemetry/model evidence is available to determine this.\n\n"
                "CyberSentinel is awaiting active live network flows or a scenario replay stream. "
                "Once telemetry is ingested by `LiveIngestService`, deterministic predictions will populate automatically."
            )

        cur = evidence.get("current_stage", "Benign")
        nxt = evidence.get("predicted_next_stage", "Benign")
        atk = evidence.get("attack_probability")
        atk_pct = f"{atk * 100:.1f}%" if atk is not None else "N/A"
        conf = evidence.get("confidence")
        conf_pct = f"{conf * 100:.1f}%" if conf is not None else "N/A"
        score = evidence.get("risk_score", 0.0)
        level = evidence.get("risk_level", "LOW")
        priority = evidence.get("recommended_priority", "P4 — Monitor")
        tid = evidence.get("primary_technique_id") or "N/A"
        tname = evidence.get("primary_technique_name") or "None"

        actions = STAGE_ACTIONS.get(cur, [
            "Maintain continuous telemetry monitoring.",
            "Verify perimeter firewall logs.",
            "Audit access logs for anomalous session activity.",
        ])
        action_bullets = "\n".join(f"• {a}" for a in actions)

        feats = evidence.get("features", [])
        if feats:
            feat_bullets = "\n".join(
                f"• `{f['feature']}` shifted from {f['current']} to {f['predicted']} ({f['rel_change_pct']:+.1f}%)"
                for f in feats[:3]
            )
        else:
            feat_bullets = "• All telemetry features remain within baseline standard deviation."

        rollout = evidence.get("rollout", [])
        rollout_str = (
            ", then ".join(f"{r['predicted_stage']} (+{r['step']})" for r in rollout)
            if rollout
            else f"Projected transition to {nxt}"
        )

        return (
            f"### **Current Assessment**\n"
            f"- **Active Stage**: **{cur}**\n"
            f"- **Predicted Next Stage**: **{nxt}** ({rollout_str})\n"
            f"- **Composite Risk**: **{score:.1f}/100** ({level}) | **Priority**: {priority}\n"
            f"- **Attack Probability**: **{atk_pct}** (Model Confidence: {conf_pct})\n"
            f"- **Primary MITRE Technique**: `{tid}` — *{tname}*\n\n"
            f"### **Empirical Telemetry Indicators**\n"
            f"{feat_bullets}\n\n"
            f"### **Recommended SOC Playbook Actions**\n"
            f"{action_bullets}\n\n"
            f"*(Generated by CyberSentinel Grounded Rule Engine)*"
        )
